config:
  allow_enchanted: 'false'
  econ_fractioning: 'on'
  item_rounding: round
  economy: 'false'
  permissions: 'true'
  auto-repair: 'true'
  repair-costs: false-nomessages
recipes:
  LEATHER_HELMET:
    normal:
      LEATHER: 5
      cost-type: both
      econ-cost: 6
  LEATHER_CHESTPLATE:
    normal:
      LEATHER: 8
      cost-type: both
      econ-cost: 6
  LEATHER_LEGGINGS:
    normal:
      LEATHER: 7
      cost-type: both
      econ-cost: 6
  LEATHER_BOOTS:
    normal:
      LEATHER: 4
      cost-type: both
      econ-cost: 6
  IRON_HELMET:
    normal:
      IRON_INGOT: 5
      cost-type: both
      econ-cost: 6
  IRON_CHESTPLATE:
    normal:
      IRON_INGOT: 8
      cost-type: both
      econ-cost: 6
  IRON_LEGGINGS:
    normal:
      IRON_INGOT: 7
      cost-type: both
      econ-cost: 6
  IRON_BOOTS:
    normal:
      IRON_INGOT: 4
      cost-type: both
      econ-cost: 6
  DIAMOND_HELMET:
    normal:
      DIAMOND: 5
      cost-type: both
      econ-cost: 6
  DIAMOND_CHESTPLATE:
    normal:
      DIAMOND: 8
      cost-type: both
      econ-cost: 6
  DIAMOND_LEGGINGS:
    normal:
      DIAMOND: 7
      cost-type: both
      econ-cost: 6
  DIAMOND_BOOTS:
    normal:
      DIAMOND: 4
      cost-type: both
      econ-cost: 6
  GOLD_HELMET:
    normal:
      GOLD_INGOT: 5
      cost-type: both
      econ-cost: 6
  GOLD_CHESTPLATE:
    normal:
      GOLD_INGOT: 8
      cost-type: both
      econ-cost: 6
  GOLD_LEGGINGS:
    normal:
      GOLD_INGOT: 7
      cost-type: both
      econ-cost: 6
  GOLD_BOOTS:
    normal:
      GOLD_INGOT: 4
      cost-type: both
      econ-cost: 6
  CHAINMAIL_HELMET:
    normal:
      IRON_INGOT: 5
      cost-type: both
      econ-cost: 6
  CHAINMAIL_CHESTPLATE:
    normal:
      IRON_INGOT: 8
      cost-type: both
      econ-cost: 6
  CHAINMAIL_LEGGINGS:
    normal:
      IRON_INGOT: 7
      cost-type: both
      econ-cost: 6
  CHAINMAIL_BOOTS:
    normal:
      IRON_INGOT: 4
      cost-type: both
      econ-cost: 6
  GOLD_HOE:
    normal:
      STICK: 2
      GOLD_INGOT: 3
      cost-type: item
      econ-cost: 6
  GOLD_SPADE:
    normal:
      STICK: 1
      GOLD_INGOT: 3
      cost-type: item
      econ-cost: 6
  GOLD_PICKAXE:
    normal:
      STICK: 2
      GOLD_INGOT: 3
      cost-type: item
      econ-cost: 6
  GOLD_AXE:
    normal:
      STICK: 2
      GOLD_INGOT: 3
      cost-type: item
      econ-cost: 6
  WOOD_HOE:
    normal:
      STICK: 2
      cost-type: item
      econ-cost: 6
      WOOD: 3
  WOOD_SPADE:
    normal:
      STICK: 2
      cost-type: item
      econ-cost: 6
      WOOD: 1
  WOOD_PICKAXE:
    normal:
      STICK: 2
      cost-type: item
      econ-cost: 6
      WOOD: 3
  WOOD_AXE:
    normal:
      STICK: 2
      cost-type: item
      econ-cost: 6
      WOOD: 3
  STONE_HOE:
    normal:
      COBBLESTONE: 3
      STICK: 2
      cost-type: item
      econ-cost: 6
    normal:
      COBBLESTONE: 1
      STICK: 2
      cost-type: item
      econ-cost: 6
  STONE_PICKAXE:
    normal:
      COBBLESTONE: 3
      STICK: 2
      cost-type: item
      econ-cost: 6
  STONE_AXE:
    normal:
      COBBLESTONE: 3
      STICK: 2
      cost-type: item
      econ-cost: 6
  IRON_HOE:
    normal:
      IRON_INGOT: 3
      STICK: 2
      cost-type: item
      econ-cost: 6
  IRON_SPADE:
    normal:
      IRON_INGOT: 1
      STICK: 2
      cost-type: item
      econ-cost: 6
  IRON_PICKAXE:
    normal:
      IRON_INGOT: 3
      STICK: 2
      cost-type: item
      econ-cost: 6
  IRON_AXE:
    normal:
      IRON_INGOT: 3
      STICK: 2
      cost-type: item
      econ-cost: 6
  DIAMOND_HOE:
    normal:
      DIAMOND: 3
      STICK: 2
      cost-type: item
      econ-cost: 6
  DIAMOND_SPADE:
    normal:
      DIAMOND: 1
      STICK: 2
      cost-type: item
      econ-cost: 6
  DIAMOND_PICKAXE:
    normal:
      DIAMOND: 3
      STICK: 2
      cost-type: item
      econ-cost: 6
  DIAMOND_AXE:
    normal:
      DIAMOND: 3
      STICK: 2
      cost-type: item
      econ-cost: 6
  FLINT_AND_STEEL:
    normal:
      IRON_INGOT: 1
      cost-type: item
      FLINT: 1
      econ-cost: 6
  FISHING_ROD:
    normal:
      STICK: 3
      cost-type: item
      econ-cost: 6
      STRING: 2
  SHEARS:
    normal:
      IRON_INGOT: 2
      cost-type: both
      econ-cost: 6
  BOW:
    normal:
      STICK: 3
      cost-type: item
      econ-cost: 6
      STRING: 3
  WOOD_SWORD:
    normal:
      STICK: 1
      cost-type: item
      econ-cost: 6
      WOOD: 2
  GOLD_SWORD:
    normal:
      STICK: 1
      GOLD_INGOT: 2
      cost-type: item
      econ-cost: 6
  STONE_SWORD:
    normal:
      COBBLESTONE: 2
      STICK: 1
      cost-type: item
      econ-cost: 6
  IRON_SWORD:
    normal:
      IRON_INGOT: 2
      STICK: 1
      cost-type: item
      econ-cost: 6
  DIAMOND_SWORD:
    normal:
      DIAMOND: 2
      STICK: 1
      cost-type: item
      econ-cost: 6
