recipes:
  LEATHER_HELMET:
    normal:
  LEATHER_CHESTPLATE:
    normal:
  LEATHER_LEGGINGS:
    normal:
  LEATHER_BOOTS:
    normal:
  IRON_HELMET:
    normal:
  IRON_CHESTPLATE:
    normal:
  IRON_LEGGINGS:
    normal:
  IRON_BOOTS:
    normal:
  DIAMOND_HELMET:
    normal:
  DIAMOND_CHESTPLATE:
    normal:
  DIAMOND_LEGGINGS:
    normal:
  DIAMOND_BOOTS:
    normal:
  GOLD_HELMET:
    normal:
  GOLD_CHESTPLATE:
    normal:
  GOLD_LEGGINGS:
    normal:
  GOLD_BOOTS:
    normal:
  CHAINMAIL_HELMET:
    normal:
  CHAINMAIL_CHESTPLATE:
    normal:
  CHAINMAIL_LEGGINGS:
    normal:
  CHAINMAIL_BOOTS:
    normal:
  GOLD_HOE:
    normal:
  GOLD_SPADE:
    normal:
  GOLD_PICKAXE:
    normal:
  GOLD_AXE:
    normal:
  WOOD_HOE:
    normal:
  WOOD_SPADE:
    normal:
  WOOD_PICKAXE:
    normal:
  WOOD_AXE:
    normal:
  STONE_HOE:
    normal:
  STONE_SPADE:
    normal:
  STONE_PICKAXE:
    normal:
  STONE_AXE:
    normal:
  IRON_HOE:
    normal:
  IRON_SPADE:
    normal:
  IRON_PICKAXE:
    normal:
  IRON_AXE:
    normal:
  DIAMOND_HOE:
    normal:
  DIAMOND_SPADE:
    normal:
  DIAMOND_PICKAXE:
    normal:
  DIAMOND_AXE:
    normal:
  FLINT_AND_STEEL:
    normal:
  FISHING_ROD:
    normal:
  SHEARS:
    normal:
  BOW:
    normal:
  WOOD_SWORD:
    normal:
  GOLD_SWORD:
    normal:
  STONE_SWORD:
    normal:
  IRON_SWORD:
    normal:
  DIAMOND_SWORD:
    normal:
config:
  allowRepairOfEnchantedItems: true
  usePermissions: false
  automaticRepair: true
  allowAnvilUse: true
  econCost: full
  xpCost: full
  itemCost: full
